// Code generated by "stringer -type ReleaseType -linecomment -output release_type_string.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlphaRelease-0]
	_ = x[BetaRelease-1]
	_ = x[MajorRelease-2]
	_ = x[MinorRelease-3]
	_ = x[MaintenanceRelease-4]
}

const _ReleaseType_name = "Alpha ReleaseBeta ReleaseMajor ReleaseMinor ReleaseMaintenance Release"

var _ReleaseType_index = [...]uint8{0, 13, 25, 38, 51, 70}

func (i ReleaseType) String() string {
	if i < 0 || i >= ReleaseType(len(_ReleaseType_index)-1) {
		return "ReleaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReleaseType_name[_ReleaseType_index[i]:_ReleaseType_index[i+1]]
}
