// Code generated by "stringer -type FlagName -linecomment -output flag_string.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlagNameMetaFilePath-0]
	_ = x[FlagNameSearchPath-1]
	_ = x[FlagNameVerbose-2]
	_ = x[FlagNameGpdbVersion-3]
}

const _FlagName_name = "metadatasearch-pathverbosegpdb-version"

var _FlagName_index = [...]uint8{0, 8, 19, 26, 38}

func (i FlagName) String() string {
	if i < 0 || i >= FlagName(len(_FlagName_index)-1) {
		return "FlagName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlagName_name[_FlagName_index[i]:_FlagName_index[i+1]]
}
